// this is all stuff that was not autogenerated during the terminal 
// command creatiion of packages and files
import express from "express";
import cors from "cors";

const app=express(); // creates app
app.use(cors()); // mounts middleware, which cors is. not sure how cors 
// is a method though...

// come back to this here, but this is what the get request
// from front end 'gets' and then displays
app.get("/getData",(req,res)=>{ 
    res.send("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.");
});

app.listen(3001,()=>console.log("app is running")); // express method
// parameters are listen(port number, action taken when port is listened to)
// video shows using port 5000 but got a lot of weird errors about port being 
// used. tried commands like  sudo lsof -i :5000 to see what was using 5000 
// and tried to kill the PID with kill -9 <PID number>  but didn't work. port
// switch worked though. there are a shit ton of different ports. 65000. I can 
// literally pick pretty much anything. 3001 works. 3002. 3000 is just used 
// conventionally and is a nice round number